### PR TITLE
revamp + autoinstall in bat

### PR DESCRIPTION
**Pull request by itsweekly**
yea yea

### CODE REVIEW

**Review by KaneDbD — APPROVED** [review]
ultrahd

**Comment by itsweekly** [comment]
lolmanurfunny, inside the installer.bat file theres the link to the exe, which is now in the src folder inside "patcher" you will have to change the link to that exe and thats it

**Comment by klobyy** [comment]
decent

**Comment by lolmanurfunny** [comment]
I'd rather not require UAC privileges.

**Comment by itsweekly** [comment]
> I'd rather not require UAC privileges.

it does not require uac i never said it does the only reason it runs as administrator is to make sure it has enough perms to goto folders like app data etc.. its a precaution

**Comment by lolmanurfunny** [comment]
I see

**Comment by itsweekly** [comment]
> I see

will you take the bat version alone or keep the python? this doesnt need any requirements so i think its better

**Comment by itsweekly** [comment]
> > will you take the bat version alone or keep the python? this doesnt need any requirements so i think its better
> 
> I'll keep the python. The precompiled binaries are standalone and thus don't require a python installation.

this it a auto installer so it auto replaces the old roblox exe with the current one idk if your python has that?

**Comment by lolmanurfunny** [comment]
> this it a auto installer so it auto replaces the old roblox exe with the current one idk if your python has that?

see [Patch Nabber](https://github.com/lolmanurfunny/Roblox-Launcher-minus-the-app/tags)

**Pull request closed without merging**
