### PR TITLE
Substantially refactored Python scripts to make them more in line with common convention; made variable and function names more descriptive.

### PR DESCRIPTION
**Pull request by Windows81**
**I highly recommend you test my changes out!**  They substantially affect how the code is structured.

### CODE REVIEW

**Review by lolmanurfunny — APPROVED** [review]

**Comment by localfossa** [comment]
For me, I think it is unnecessary to use functions for just one thing but for others yeah it is good

**Comment by Windows81** [comment]
Many design paradigms promote having functions that do one thing and one thing only, such as 'functional programming'.  It makes it easier to group small tasks into larger ones.  That's called abstraction.

**Comment by localfossa** [comment]
> Many design paradigms promote having functions that do one thing and one thing only, such as 'functional programming'. It makes it easier to group small tasks into larger ones. That's called abstraction.

I said **For me**. Also I already know that.

**Comment by lolmanurfunny** [comment]
> It looks good for cosmetic but creating functions uses **more memory.**

Yeah I was thinking the same thing immediately after approving it.

**Pull request closed without merging**
